version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.txt
    ports:
      - 80:80
    volumes: 
      - ".:/var/www/html"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:5.2
    ports:
      - 8080:80
    environment:
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - "./estrutura_do_banco.sql:/initial/estrutura_do_banco.sql"
    # Rode um dos comandos abaixo a partir do bash para popular o database 
    # (espere o banco de dados aceitar conexões primeiro):
    #   mysql blog -u$MYSQL_USER -p$MYSQL_PASSWORD < /initial/estrutura_do_banco.sql
    #   mysql --user=user --password=senha blog < /initial/estrutura_do_banco.sql
    #   mysql -uroot -proot blog < /initial/estrutura_do_banco.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=senha
